spring:
  application:
    name: post-service

  datasource:
    url: jdbc:postgresql://localhost:5432/linkup-post
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9010
  servlet:
    context-path: /posts

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka